# Mehr Speicher f??r Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric (siehe https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod
mod_version=1.0.7
maven_group=de.mclauncher
archives_base_name=mclauncher-badge
